import type { ApiSupabaseClient } from "@/lib/supabase/api";
import { throwDatabaseError } from "@/lib/api/response";
import type { FinanceCategory, FinanceCategoryInput, FinanceDashboardData, FinanceFileAttachment, FinanceInput, FinanceLinkAttachment, FinanceSummary, FinanceTransaction } from "@/types/finance";
const CATEGORY_FIELDS="id,ten,loai,ngan_sach_thang";
const TRANSACTION_FIELDS="id,loai,so_tien,ngay,danh_muc_id,mo_ta,tep_hoa_don,created_at,thu_chi_danh_muc(id,ten,loai,ngan_sach_thang)";
const mapCategory=(r:Record<string,unknown>):FinanceCategory=>({id:String(r.id),name:String(r.ten),type:r.loai as FinanceCategory["type"],monthlyBudget:r.ngan_sach_thang==null?undefined:Number(r.ngan_sach_thang)});
function parseReceiptData(value:unknown):{images:string[];files:FinanceFileAttachment[];links:FinanceLinkAttachment[]}{
  if(typeof value!=="string"||!value.trim())return {images:[],files:[],links:[]};
  try{const parsed=JSON.parse(value) as Record<string,unknown>;return {images:Array.isArray(parsed.images)?parsed.images.filter((item):item is string=>typeof item==="string"):[],files:Array.isArray(parsed.files)?parsed.files.filter((item):item is FinanceFileAttachment=>Boolean(item)&&typeof item==="object"&&typeof (item as FinanceFileAttachment).name==="string"&&typeof (item as FinanceFileAttachment).url==="string"):[],links:Array.isArray(parsed.links)?parsed.links.filter((item):item is FinanceLinkAttachment=>Boolean(item)&&typeof item==="object"&&typeof (item as FinanceLinkAttachment).url==="string"):[]};}
  catch{return {images:[],files:[],links:[{url:value}]};}
}
function serializeReceiptData(input:FinanceInput){const data={images:input.receiptImages??[],files:input.receiptFiles??[],links:input.receiptLinks??[]};return data.images.length||data.files.length||data.links.length?JSON.stringify(data):null;}
const mapTransaction=(r:Record<string,unknown>):FinanceTransaction=>{const receipt=parseReceiptData(r.tep_hoa_don);return {id:String(r.id),type:r.loai as FinanceTransaction["type"],amount:Number(r.so_tien),date:String(r.ngay),categoryId:String(r.danh_muc_id),category:r.thu_chi_danh_muc?mapCategory(Array.isArray(r.thu_chi_danh_muc)?r.thu_chi_danh_muc[0] as Record<string,unknown>:r.thu_chi_danh_muc as Record<string,unknown>):undefined,description:r.mo_ta as string|undefined,receiptImages:receipt.images,receiptFiles:receipt.files,receiptLinks:receipt.links,receiptUrl:receipt.images[0]??receipt.files[0]?.url??receipt.links[0]?.url,createdAt:String(r.created_at)};};
export async function listFinanceCategories(s:ApiSupabaseClient){const {data,error}=await s.from("thu_chi_danh_muc").select(CATEGORY_FIELDS).order("ten");throwDatabaseError(error);return (data??[]).map(r=>mapCategory(r as Record<string,unknown>));}
export async function listFinanceTransactions(s:ApiSupabaseClient,page:number,size:number,type?:string,categoryIds:string[]=[],start?:string,end?:string,search?:string,sort="date",direction="desc"){
  const sortColumns:Record<string,string>={date:"ngay",amount:"so_tien",createdAt:"created_at"};
  let q=s.from("thu_chi").select(TRANSACTION_FIELDS,{count:"exact"}).order(sortColumns[sort]??"ngay",{ascending:direction==="asc"}).range((page-1)*size,page*size-1);
  if(type)q=q.eq("loai",type);if(categoryIds.length)q=q.in("danh_muc_id",categoryIds);if(start)q=q.gte("ngay",start);if(end)q=q.lte("ngay",end);if(search)q=q.ilike("mo_ta",`%${search}%`);
  const {data,error,count}=await q;throwDatabaseError(error);return {items:(data??[]).map(r=>mapTransaction(r as Record<string,unknown>)),total:count??0};
}
export async function createFinanceTransaction(s:ApiSupabaseClient,input:FinanceInput){const {data,error}=await s.from("thu_chi").insert({loai:input.type,so_tien:input.amount,ngay:input.date,danh_muc_id:input.categoryId,mo_ta:input.description??null,tep_hoa_don:serializeReceiptData(input)}).select(TRANSACTION_FIELDS).single();throwDatabaseError(error);return mapTransaction(data as Record<string,unknown>);}
export async function updateFinanceTransaction(s:ApiSupabaseClient,id:string,input:FinanceInput){const {data,error}=await s.from("thu_chi").update({loai:input.type,so_tien:input.amount,ngay:input.date,danh_muc_id:input.categoryId,mo_ta:input.description??null,tep_hoa_don:serializeReceiptData(input)}).eq("id",id).select(TRANSACTION_FIELDS).maybeSingle();throwDatabaseError(error);return data?mapTransaction(data as Record<string,unknown>):null;}
export async function deleteFinanceTransaction(s:ApiSupabaseClient,id:string){const {data,error}=await s.from("thu_chi").delete().eq("id",id).select("id").maybeSingle();throwDatabaseError(error);return Boolean(data);}
export async function createFinanceCategory(s:ApiSupabaseClient,input:FinanceCategoryInput){const {data,error}=await s.from("thu_chi_danh_muc").insert({ten:input.name,loai:input.type,ngan_sach_thang:input.monthlyBudget??null}).select(CATEGORY_FIELDS).single();throwDatabaseError(error);return mapCategory(data as Record<string,unknown>);}
export async function updateFinanceCategory(s:ApiSupabaseClient,id:string,input:FinanceCategoryInput){const {data,error}=await s.from("thu_chi_danh_muc").update({ten:input.name,loai:input.type,ngan_sach_thang:input.monthlyBudget??null}).eq("id",id).select(CATEGORY_FIELDS).maybeSingle();throwDatabaseError(error);return data?mapCategory(data as Record<string,unknown>):null;}
export async function deleteFinanceCategory(s:ApiSupabaseClient,id:string){const {data,error}=await s.from("thu_chi_danh_muc").delete().eq("id",id).select("id").maybeSingle();throwDatabaseError(error);return Boolean(data);}
function buildFinanceSummary(data:unknown[]|null,categories:unknown[]|null,expenses:unknown[]|null):FinanceSummary{const series=((data??[]) as Record<string,unknown>[]).map(r=>({date:String(r.ngay),type:r.loai as FinanceTransaction["type"],amount:Number(r.tong_tien)}));const income=series.filter(x=>x.type==="thu").reduce((a,x)=>a+x.amount,0),expense=series.filter(x=>x.type==="chi").reduce((a,x)=>a+x.amount,0);const spentByCategory=new Map<string,number>();for(const raw of expenses??[]){const row=raw as Record<string,unknown>;spentByCategory.set(String(row.danh_muc_id),(spentByCategory.get(String(row.danh_muc_id))??0)+Number(row.so_tien));}return {income,expense,series,budgets:((categories??[]) as Record<string,unknown>[]).filter(r=>r.loai==="chi").map(r=>({category:mapCategory(r),spent:spentByCategory.get(String(r.id))??0})).sort((a,b)=>b.spent-a.spent)};}
export async function financeSummary(s:ApiSupabaseClient,start:string,end:string):Promise<FinanceSummary>{const [{data,error},{data:categories,error:categoryError},{data:expenses,error:expenseError}]=await Promise.all([s.rpc("thu_chi_tong_hop",{p_start:start,p_end:end}),s.from("thu_chi_danh_muc").select(CATEGORY_FIELDS),s.from("thu_chi").select("danh_muc_id,so_tien").eq("loai","chi").gte("ngay",start).lte("ngay",end)]);throwDatabaseError(error);throwDatabaseError(categoryError);throwDatabaseError(expenseError);return buildFinanceSummary(data,categories,expenses);}
export async function financeDashboard(s:ApiSupabaseClient,page:number,size:number,type:string|undefined,categoryIds:string[],start:string,end:string,search?:string,sort="date",direction="desc"):Promise<FinanceDashboardData>{const [seriesResult,categoryResult,expenseResult,transactions]=await Promise.all([s.rpc("thu_chi_tong_hop",{p_start:start,p_end:end}),s.from("thu_chi_danh_muc").select(CATEGORY_FIELDS).order("ten"),s.from("thu_chi").select("danh_muc_id,so_tien").eq("loai","chi").gte("ngay",start).lte("ngay",end),listFinanceTransactions(s,page,size,type,categoryIds,start,end,search,sort,direction)]);throwDatabaseError(seriesResult.error);throwDatabaseError(categoryResult.error);throwDatabaseError(expenseResult.error);return {categories:(categoryResult.data??[]).map(r=>mapCategory(r as Record<string,unknown>)),summary:buildFinanceSummary(seriesResult.data,categoryResult.data,expenseResult.data),transactions};}
