import type { Subtask, SubtaskReport } from "@/types/subtask";

export const INITIAL_SUBTASKS: Subtask[] = [
  {
    id: "tk-1",
    title: "Gắn Switch vào tủ Rack",
    description: "Lắp đặt Switch cố định vào tủ Rack tầng kỹ thuật, đấu nối nguồn điện.",
    workTaskId: "cv-1",
    assigneeId: "nv-002",
    status: "done",
    priority: "high",
    startDate: "2026-05-01",
    dueDate: "2026-05-10",
    progress: 100,
    tags: ["Lắp đặt"],
    assignees: [],
    acceptedAssigneeIds: [],
    files: [],
    links: [],
    images: [],
    updates: [],
  },
  {
    id: "tk-2",
    title: "Đấu nối Patch Panel",
    description: "Đấu nối các cổng Patch Panel với Switch theo sơ đồ đã thiết kế.",
    workTaskId: "cv-1",
    assigneeId: "nv-003",
    status: "inProgress",
    priority: "high",
    startDate: "2026-05-08",
    dueDate: "2026-06-05",
    progress: 60,
    tags: ["Thi công"],
    assignees: [],
    acceptedAssigneeIds: [],
    files: [],
    links: [],
    images: [],
    updates: [],
  },
  {
    id: "tk-3",
    title: "Cấu hình VLAN nội bộ",
    description: "Tạo và gán các VLAN cho từng phòng ban theo yêu cầu bảo mật.",
    workTaskId: "cv-1",
    assigneeId: "nv-005",
    status: "todo",
    priority: "urgent",
    startDate: "2026-06-10",
    dueDate: "2026-06-25",
    progress: 0,
    tags: ["Cấu hình"],
    assignees: [],
    acceptedAssigneeIds: [],
    files: [],
    links: [],
    images: [],
    updates: [],
  },
  {
    id: "tk-4",
    title: "Bấm đầu dây tầng 1",
    description: "Bấm đầu chuẩn T568B cho toàn bộ dây cáp tầng 1.",
    workTaskId: "cv-2",
    assigneeId: "nv-003",
    status: "todo",
    priority: "medium",
    startDate: "2026-06-20",
    dueDate: "2026-07-10",
    progress: 0,
    tags: ["Thi công"],
    assignees: [],
    acceptedAssigneeIds: [],
    files: [],
    links: [],
    images: [],
    updates: [],
  },
  {
    id: "tk-5",
    title: "Bấm đầu dây tầng 2",
    description: "Bấm đầu chuẩn T568B cho toàn bộ dây cáp tầng 2.",
    workTaskId: "cv-2",
    assigneeId: "nv-004",
    status: "todo",
    priority: "medium",
    startDate: "2026-06-25",
    dueDate: "2026-07-15",
    progress: 0,
    tags: ["Thi công"],
    assignees: [],
    acceptedAssigneeIds: [],
    files: [],
    links: [],
    images: [],
    updates: [],
  },
  {
    id: "tk-6",
    title: "Kéo cáp tầng 1",
    description: "Kéo dây cáp mạng Cat6 từ phòng kỹ thuật xuống các phòng ban tầng 1.",
    workTaskId: "cv-3",
    assigneeId: "nv-001",
    status: "done",
    priority: "high",
    startDate: "2026-04-30",
    dueDate: "2026-05-25",
    progress: 100,
    tags: ["Thi công"],
    assignees: [],
    acceptedAssigneeIds: [],
    files: [],
    links: [],
    images: [],
    updates: [],
  },
  {
    id: "tk-7",
    title: "Kéo cáp tầng 2",
    description: "Kéo dây cáp mạng Cat6 từ phòng kỹ thuật xuống các phòng ban tầng 2.",
    workTaskId: "cv-3",
    assigneeId: "nv-002",
    status: "inProgress",
    priority: "high",
    startDate: "2026-05-20",
    dueDate: "2026-06-30",
    progress: 50,
    tags: ["Thi công"],
    assignees: [],
    acceptedAssigneeIds: [],
    files: [],
    links: [],
    images: [],
    updates: [],
  },
  {
    id: "tk-8",
    title: "Khảo sát tầng 1-5",
    description: "Khảo sát thực tế đường đi dây cho các tầng 1 đến 5.",
    workTaskId: "cv-4",
    assigneeId: "nv-002",
    status: "done",
    priority: "high",
    startDate: "2026-01-15",
    dueDate: "2026-01-25",
    progress: 100,
    tags: ["Khảo sát"],
    assignees: [],
    acceptedAssigneeIds: [],
    files: [],
    links: [],
    images: [],
    updates: [],
  },
  {
    id: "tk-9",
    title: "Khảo sát tầng 6-10",
    description: "Khảo sát thực tế đường đi dây cho các tầng 6 đến 10.",
    workTaskId: "cv-4",
    assigneeId: "nv-005",
    status: "done",
    priority: "high",
    startDate: "2026-01-26",
    dueDate: "2026-02-10",
    progress: 100,
    tags: ["Khảo sát"],
    assignees: [],
    acceptedAssigneeIds: [],
    files: [],
    links: [],
    images: [],
    updates: [],
  },
  {
    id: "tk-10",
    title: "Thiết kế giao diện Dashboard",
    description: "Thiết kế Figma cho màn hình Dashboard tổng quan.",
    workTaskId: "cv-5",
    assigneeId: "nv-001",
    status: "done",
    priority: "medium",
    startDate: "2025-04-01",
    dueDate: "2025-04-25",
    progress: 100,
    tags: ["UI/UX"],
    assignees: [],
    acceptedAssigneeIds: [],
    files: [],
    links: [],
    images: [],
    updates: [],
  },
  {
    id: "tk-11",
    title: "Thiết kế giao diện Chấm công",
    description: "Thiết kế Figma cho phân hệ Chấm công nhân sự.",
    workTaskId: "cv-5",
    assigneeId: "nv-001",
    status: "done",
    priority: "medium",
    startDate: "2025-04-20",
    dueDate: "2025-05-20",
    progress: 100,
    tags: ["UI/UX"],
    assignees: [],
    acceptedAssigneeIds: [],
    files: [],
    links: [],
    images: [],
    updates: [],
  },
];

export const SUBTASK_REPORTS: SubtaskReport[] = [];
