import type { WorkTask, TaskReport } from "@/types/task";

export const INITIAL_TASKS: WorkTask[] = [
  {
    id: "cv-1",
    title: "Cấu hình thiết bị Switch và Wifi AP",
    description: "Gắn Switch vào tủ Rack, đấu nối Patch Panel và cấu hình các VLAN nội bộ.",
    projectId: "2",
    assigneeId: "nv-002",
    status: "review",
    priority: "urgent",
    startDate: "2026-05-01",
    dueDate: "2026-06-25",
    progress: 90,
    tags: ["Hạ tầng", "Mạng"],
    assignees: [],
    files: [],
    links: [],
    images: [],
  },
  {
    id: "cv-2",
    title: "Bấm đầu mạng RJ45 và nối Patch Panel",
    description: "Bấm đầu chuẩn T568B cho toàn bộ dây cáp và đấu nối vào Patch Panel tầng 1.",
    projectId: "2",
    assigneeId: "nv-003",
    status: "todo",
    priority: "medium",
    startDate: "2026-06-20",
    dueDate: "2026-07-15",
    progress: 0,
    tags: ["Thi công"],
    assignees: [],
    files: [],
    links: [],
    images: [],
  },
  {
    id: "cv-3",
    title: "Kéo cáp mạng LAN tầng 1 và 2",
    description: "Kéo dây cáp mạng Cat6 từ phòng kỹ thuật xuống các phòng ban tầng 1 và tầng 2.",
    projectId: "2",
    assigneeId: "nv-001",
    status: "inProgress",
    priority: "high",
    startDate: "2026-04-30",
    dueDate: "2026-06-30",
    progress: 80,
    tags: ["Thi công", "Mạng"],
    assignees: [],
    files: [],
    links: [],
    images: [],
  },
  {
    id: "cv-4",
    title: "Khảo sát mặt bằng tòa nhà A",
    description: "Khảo sát thực tế các tầng lầu của Tòa nhà A để lập đường đi dây tối ưu nhất.",
    projectId: "2",
    assigneeId: "nv-002",
    status: "done",
    priority: "high",
    startDate: "2026-01-15",
    dueDate: "2026-02-10",
    progress: 100,
    tags: ["Khảo sát"],
    assignees: [],
    files: [],
    links: [],
    images: [],
  },
  {
    id: "cv-5",
    title: "Thiết kế Mockup UI/UX hệ thống App Goal",
    description: "Thiết kế giao diện Figma cho phân hệ Dashboard và Chấm công.",
    projectId: "1",
    assigneeId: "nv-001",
    status: "done",
    priority: "medium",
    startDate: "2025-04-01",
    dueDate: "2025-05-20",
    progress: 100,
    tags: ["UI/UX"],
    assignees: [],
    files: [],
    links: [],
    images: [],
  },
];

export const TASK_REPORTS: TaskReport[] = [];
